name: Continuous integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal toolchain with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Run tests
        # test threads must be one because else database tests will run in parallel and will result in flaky tests
        run: cargo test --all-features --verbose -- --test-threads=1
      - name: Format check
        run: cargo fmt --all -- --check
        # Ensure that all targets compile and pass clippy checks under every possible combination of features
      - name: Clippy check
        run: cargo install cargo-hack --version 0.5.18 && cargo hack --feature-powerset clippy --locked --release
